export const SET_ACTIVE_HEADER_MENU = 'SET_ACTIVE_HEADER_MENU' as const
export const SET_ACTIVE_SIDEBAR = 'SET_ACTIVE_SIDEBAR' as const
export const SET_USER_DATA = 'SET_USER_DATA' as const
export const SET_PASSWORD_STATUS = 'SET_PASSWORD_STATUS' as const
// export const SET_AUTH = 'SET_AUTH';
export const SET_USER_QUERIED = 'SET_USER_QUERIED' as const
export const SET_HEADER_MENUS = 'SET_HEADER_MENUS' as const
export const SET_FULLSCREEN = 'SET_FULLSCREEN' as const
export const SET_PRINT_MODE = 'SET_PRINT_MODE' as const
export const SET_KEEP_ROUTES = 'SET_KEEP_ROUTES' as const
export const SET_SYSTEM_CONFIG = 'SET_SYSTEM_CONFIG' as const
export const SET_ONLINE = 'SET_ONLINE'as const